### ISSUE TITLE
Implement GxB_get/set

### ISSUE THREAD

**Issue by FlorentinD** [fabianmurariu/graphblas-java-native#6]
Currently we can set options for matrices (e.g. the `hyperRatio`), but not global parameters .
For global options, `GxB_get`/`GxB_set` is used.

My main use-case is setting/limiting the number of threads.

I would volunteer to implement this mapping as well.

**Comment by FlorentinD** [comment]
I implemented it on my fork .. if you are interested I can create a PR :)

**Comment by fabianmurariu** [comment]
Do create a PR when you can, I will merge it
